server:
  port: 5555

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: CCD Test Stubs Services

wiremock:
  server:
    host: localhost
    port: 5560
    mappings-path: ${WIREMOCK_SERVER_MAPPINGS_PATH:wiremock}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.github.tomakehurst: WARN
