server:
  port: 5555

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: CCD Test Stubs Services

wiremock:
  server:
    host: localhost
    mappings-path: ${WIREMOCK_SERVER_MAPPINGS_PATH:wiremock}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.github.tomakehurst: INFO

app:
  management-web-url: ${MANAGEMENT_WEB_URL:http://localhost:3451}
